server {
    listen ${PORT};
    server_name _;

    location / {
        # ชี้ proxy_pass ไปที่ Service PHP ของ Railway
        proxy_pass http://php-railway-project.railway.internal:8080;
        
        # ส่งป้ายบอก PHP ว่าวิ่งผ่าน Nginx
        proxy_set_header X-Server-Type "NGINX";
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
