server {
    listen ${PORT};
    server_name _;

    location / {
        # 1. เปลี่ยนเป็น Private Domain ของฝั่ง PHP (ต้องใช้ http:// และต่อพอร์ต :8080)
        proxy_pass http://php-railway-project.railway.internal:8080;

        # 2. ตั้งค่า Header
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # 3. ส่ง Header บอก PHP ว่าร้องขอมาจาก Nginx
        proxy_set_header X-Server-Type "NGINX";
    }
}
